"use client"

import { useEffect, useRef } from "react"

import "./orbital-field.css"

/**
 * A slowly drifting field of particles behind the evidence section.
 *
 * HOW IT STAYS CHEAP — this is the whole design, not a detail. The field is 732
 * dots and the page pays for six empty divs and zero bytes of markup. The dots
 * live in orbital-field.css as six pre-rendered background layers, generated by
 * scripts/generate-orbital-field.mjs; all this component does is name them.
 *
 * Two costs were removed to get here, and both are worth knowing about because
 * neither is visible on screen:
 *
 *   PER FRAME. The first version put 732 `<circle>` elements in the DOM inside
 *   rotating `<g>`s. Rotating a div with a background image is rasterised once
 *   and then transformed on the compositor — a matrix multiply on an existing
 *   texture, and the cost does not grow with dot count. Vector geometry inside a
 *   rotating group leaves the door open to re-rasterising every frame, and puts
 *   732 nodes in the style and layout trees besides.
 *
 *   PER RESPONSE. The second version moved the dots into `style={{
 *   backgroundImage }}`, which ships them TWICE in every HTML response: once in
 *   the style attribute, and once again in the RSC flight payload React streams
 *   for hydration. Measured on the homepage that was 85KB of a 275KB document —
 *   32% of the page, for decoration, on every navigation. In a stylesheet the
 *   dots appear once, in a file the browser caches across the whole site.
 *
 * Doubling the density from here costs a few KB of cached CSS and one
 * rasterisation. It costs nothing per frame and nothing per response.
 *
 * WHY CIRCULAR BANDS AND NOT A TILTED ELLIPSE. A tilted ring is closer to the
 * reference, and the obvious way to get one — squash the field with `scale(1,
 * 0.5)` — squashes every dot with it, so round particles become visible ovals.
 * Counter-scaling each dot does not rescue it: the counter-transform applies
 * before the rotation, so it only holds at zero degrees and the dots breathe
 * from round to oval as the band turns. Circular bands rotate exactly and keep
 * their dots round; `background-size: cover` crops the 2:1 field top and bottom
 * so it still reads as a broad sweep.
 *
 * Decorative, and marked aria-hidden. The section's argument is all in its text.
 */

/** Layer count — must match BAND_SPEC in scripts/generate-orbital-field.mjs. */
const LAYERS = 6

export function OrbitalFieldBackdrop() {
  const rootRef = useRef<HTMLDivElement | null>(null)

  // Third cost, learned after the two documented above: layer RETENTION. Six
  // section-sized composited layers with will-change stay resident on the GPU
  // and keep ticking for the tab's lifetime, long after the section scrolls
  // away. Same IntersectionObserver pattern the hero (frameloop) and the
  // stacked deck (interval) already use: off-screen, animations pause and
  // will-change releases the textures. rootMargin resumes them just before
  // re-entry so the drift is never seen starting.
  useEffect(() => {
    const root = rootRef.current
    if (!root || typeof IntersectionObserver !== "function") return
    const observer = new IntersectionObserver(
      ([entry]) => {
        root.classList.toggle("mt-orbit-paused", !entry.isIntersecting)
      },
      { rootMargin: "20% 0px" },
    )
    observer.observe(root)
    return () => observer.disconnect()
  }, [])

  return (
    <div
      ref={rootRef}
      aria-hidden
      className="pointer-events-none absolute inset-0 -z-10 overflow-hidden"
    >
      <div className="absolute inset-0 bg-[#05070c]" />
      <div className="mt-orbit-sky absolute inset-0" />

      {Array.from({ length: LAYERS }, (_, i) => (
        <div key={i} className={`mt-orbit mt-orbit-${i + 1}`} />
      ))}

      {/* Softens the join where the band meets the sections above and below, so
          the dark does not land as a hard horizontal seam across the page. */}
      <div className="absolute inset-x-0 top-0 h-24 bg-gradient-to-b from-[#05070c] to-transparent" />
      <div className="absolute inset-x-0 bottom-0 h-24 bg-gradient-to-t from-[#05070c] to-transparent" />
    </div>
  )
}
